export const OPTION_LABELS: Record<string, string> = {
  company_website: 'Company website',
  landing_page: 'Landing page',
  saas_platform: 'SaaS platform',
  customer_portal: 'Customer portal',
  booking_request_platform: 'Booking or request platform',
  internal_business_tool: 'Internal business tool',
  admin_dashboard: 'Admin dashboard',
  ecommerce_payment_service: 'E-commerce or payment-enabled service',
  ai_workflow_tool: 'AI-assisted workflow tool',
  automation_integration: 'Automation or integration',
  not_sure_yet: 'Not sure yet',
  other: 'Other',
  public_pages: 'Public pages',
  user_accounts: 'User accounts',
  login_registration: 'Login and registration',
  user_roles_permissions: 'User roles or permissions',
  customer_dashboard: 'Customer dashboard',
  booking_scheduling: 'Booking or scheduling',
  request_quote_forms: 'Request or quote forms',
  file_uploads: 'File uploads',
  payments_subscriptions: 'Payments or subscriptions',
  email_notifications: 'Email notifications',
  crm_lead_workflow: 'CRM or lead workflow',
  analytics_reporting: 'Analytics or reporting',
  map_location_features: 'Map or location features',
  ai_features: 'AI-assisted features',
  third_party_integrations: 'Third-party integrations',
  multilingual_support: 'Multilingual support',
  frontend: 'Frontend design and development',
  backend: 'Backend development',
  database: 'Database setup',
  authentication: 'Authentication',
  payment_integration: 'Payment integration',
  admin_system: 'Admin system',
  api_integration: 'API integration',
  automation: 'Automation',
  deployment_hosting: 'Deployment and hosting',
  domain_setup: 'Domain setup',
  maintenance: 'Maintenance after launch',
  technical_planning: 'Technical planning only',
  asap: 'As soon as possible',
  '2_4_weeks': 'Within 2-4 weeks',
  '1_2_months': 'Within 1-2 months',
  '3_6_months': 'Within 3-6 months',
  flexible: 'Flexible timeline',
  exploring: 'Just exploring',
  under_500: 'Under 500 EUR',
  '500_1500': '500-1,500 EUR',
  '1500_3000': '1,500-3,000 EUR',
  '3000_7500': '3,000-7,500 EUR',
  '7500_15000': '7,500-15,000 EUR',
  '15000_plus': '15,000+ EUR',
  idea_only: 'Idea only',
  rough_plan: 'Rough plan exists',
  design_spec: 'Design or specification exists',
  existing_improvement: 'Existing website or app needs improvement',
  existing_new_features: 'Existing product needs new features',
  urgent: 'Urgent business need',
  stripe_payment: 'Stripe or payment provider',
  supabase: 'Supabase',
  crm: 'CRM',
  email_provider: 'Email provider',
  calendar: 'Calendar',
  maps: 'Maps',
  analytics: 'Analytics',
  ai_api: 'AI API',
  internal_system: 'Internal company system',
};

export function getOptionLabel(id: string): string {
  return OPTION_LABELS[id] || id;
}

export function getOptionLabels(ids: string[]): string[] {
  return ids.map((id) => getOptionLabel(id));
}
